import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { rowdies, permanentMarker } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rowdies.className} ${rowdies.variable} ${permanentMarker.variable} font-light`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
