import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { rowdies, permanentMarker, inter } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${rowdies.variable} ${permanentMarker.variable} ${inter.variable} bg-gray-500 font-light`}
      >
        <div className="relative mx-auto flex min-h-screen max-w-[375px] flex-col justify-between bg-white px-[16px] py-[34px]">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
